### PR TITLE
Allow writing both html and html_fragment

### LINKED ISSUE #60: Specifying both --html and --fragment outputs just the fragment
Consider:
```
nabijaczleweli@tarta:~/code/klapki/man$ ls
index.txt  klapki.md
nabijaczleweli@tarta:~/code/klapki/man$ ronn -f5 klapki.md
html_fragment: ./klapki.8.html_fragment
nabijaczleweli@tarta:~/code/klapki/man$ ls
index.txt  klapki.8.html_fragment  klapki.md
```

### PR DESCRIPTION
**Pull request by nabijaczleweli**
I was expecting this to be a weird bug and not a one-line deletion, hence the issue first.

Closes #60

### CODE REVIEW

**Comment by nabijaczleweli** [comment]
Rebased

**Comment by apjanke** [comment]
This is looking good to me. Let me do a little more testing, and then I'll slide it in for the upcoming release.

**Comment by apjanke** [comment]
Travis CI checks are failing, but it looks unrelated to this PR. I'll try to clean those up and then deal with this.

**Comment by apjanke** [comment]
Merged. This'll go out in 0.10.0.

**Comment by apjanke** [comment]
Oops. Merging this seriously broke the test suite. (I overlooked that because I thought the Travis CI failure was just a Rubocop complaint.) I reverted the change in https://github.com/apjanke/ronn-ng/commit/4bbb05a27c3e94060c7a432dae06a57e10066c21 and am rescheduling this for 0.11.0 or later.

I think I broke the GitHub workflow by reverting the change myself instead of doing a "Revert merge" on GitHub itself. Sorry. Could you re-submit this as another PR if you can figure out a way to have it not break `bundle exec rake test`?

**Pull request merged**
